//! EXT: generated by tools/gen_portraits.py -- DO NOT EDIT.
//! The Backrooms' portraits: each base texture, the parts atlas over it, and where every
//! part and eye sits, in top-origin UV (see the tool's UV note).
// A table: the renderer reads the rects and the ellipses, the tests read the rest.
#![allow(dead_code)]

/// One part: its rect in the parts atlas and its placement rect on the base, both as
/// (u0, v0, u1, v1) with v measured from the image TOP.
#[derive(Clone, Copy, Debug)]
pub struct Part {
    pub atlas: [f32; 4],
    pub place: [f32; 4],
}

/// One portrait. `parts` are in `PART_ORDER`: eyes centre left/right, eyes left
/// left/right, mouth smile/sad/angry ("left" and "right" are the image's, the viewer's).
/// `eyes` are the eye openings' ellipses as (cx, cy, rx, ry) in base UV, left then right,
/// the same for every variant.
#[derive(Clone, Copy, Debug)]
pub struct Portrait {
    pub name: &'static str,
    pub base: &'static str,
    pub parts_texture: &'static str,
    pub base_size: (u32, u32),
    pub parts_size: (u32, u32),
    pub parts: [Part; 7],
    pub eyes: [[f32; 4]; 2],
}

pub const PART_ORDER: [&str; 7] = ["eyes_center_l", "eyes_center_r", "eyes_left_l", "eyes_left_r", "mouth_smile", "mouth_sad", "mouth_angry"];

pub const PORTRAITS: [Portrait; 2] = [
    // Mona Lisa (Leonardo da Vinci, c. 1503-1506); the sheet is the user's edit
    Portrait {
        name: "mona",
        base: "portrait_mona.bmp",
        parts_texture: "portrait_mona_parts.bmp",
        base_size: (861, 1008),
        parts_size: (1024, 256),
        parts: [
            // eyes_center_l (ncc 0.57)
            Part { atlas: [0.18555, 0.58594, 0.32812, 0.92969], place: [0.32404, 0.15179, 0.40883, 0.19544] },
            // eyes_center_r (ncc 0.61)
            Part { atlas: [0.79590, 0.01562, 0.97754, 0.42578], place: [0.41580, 0.14683, 0.52381, 0.19891] },
            // eyes_left_l (ncc 0.58)
            Part { atlas: [0.33594, 0.58594, 0.47852, 0.92578], place: [0.32520, 0.15179, 0.40999, 0.19494] },
            // eyes_left_r (ncc 0.63)
            Part { atlas: [0.00391, 0.58594, 0.17773, 0.97656], place: [0.42044, 0.14683, 0.52381, 0.19643] },
            // mouth_smile (ncc 0.52)
            Part { atlas: [0.27637, 0.01562, 0.54102, 0.52344], place: [0.33914, 0.24603, 0.49652, 0.31052] },
            // mouth_sad (ncc 0.50)
            Part { atlas: [0.54883, 0.01562, 0.78809, 0.51172], place: [0.33798, 0.24702, 0.48026, 0.31002] },
            // mouth_angry (ncc 0.48)
            Part { atlas: [0.00391, 0.01562, 0.26855, 0.55469], place: [0.33449, 0.24504, 0.49187, 0.31349] },
        ],
        eyes: [[0.37121, 0.17439, 0.02571, 0.00804], [0.47312, 0.17294, 0.03419, 0.00952]],
    },
    // Girl with a Pearl Earring (Johannes Vermeer, c. 1665); the sheet is the user's edit
    Portrait {
        name: "vermeer",
        base: "portrait_vermeer.bmp",
        parts_texture: "portrait_vermeer_parts.bmp",
        base_size: (534, 531),
        parts_size: (1024, 356),
        parts: [
            // eyes_center_l (ncc 0.83)
            Part { atlas: [0.00391, 0.01124, 0.13672, 0.51124], place: [0.30150, 0.28060, 0.42884, 0.44821] },
            // eyes_center_r (ncc 0.83)
            Part { atlas: [0.14453, 0.01124, 0.36816, 0.51124], place: [0.39700, 0.28060, 0.61142, 0.44821] },
            // eyes_left_l (ncc 0.83)
            Part { atlas: [0.37598, 0.01124, 0.50879, 0.51124], place: [0.30150, 0.28060, 0.42884, 0.44821] },
            // eyes_left_r (ncc 0.83)
            Part { atlas: [0.51660, 0.01124, 0.74023, 0.51124], place: [0.39700, 0.28060, 0.61142, 0.44821] },
            // mouth_smile (ncc 0.81)
            Part { atlas: [0.00391, 0.53371, 0.29688, 0.98876], place: [0.30712, 0.46893, 0.58801, 0.62147] },
            // mouth_sad (ncc 0.81)
            Part { atlas: [0.30469, 0.53371, 0.59668, 0.98876], place: [0.30712, 0.46893, 0.58708, 0.62147] },
            // mouth_angry (ncc 0.81)
            Part { atlas: [0.60449, 0.53371, 0.89844, 0.98876], place: [0.30712, 0.46893, 0.58895, 0.62147] },
        ],
        eyes: [[0.36423, 0.34284, 0.02528, 0.01271], [0.47154, 0.35725, 0.03202, 0.01356]],
    },
];
