//! EXT: generated by tools/gen_portraits.py -- DO NOT EDIT.
//! The Backrooms' portraits: each base texture, the parts atlas over it, and where every
//! piece and eye sits, in top-origin UV (see the tool's UV note).
// A table: the renderer reads the rects and the ellipses, the tests read the rest.
#![allow(dead_code)]

/// One piece: its rect in the parts atlas and its placement rect on the base, both as
/// (u0, v0, u1, v1) with v measured from the image TOP.
#[derive(Clone, Copy, Debug)]
pub struct Part {
    pub atlas: [f32; 4],
    pub place: [f32; 4],
}

/// One portrait. `parts` are the variants in `PART_ORDER` -- eyes centre left/right, eyes
/// left left/right, mouth smile/sad/angry ("left" and "right" are the image's, the
/// viewer's) -- each a list of pieces the renderer composites over one another in order
/// (last on top): one piece on most sheets, the Hals mouths four. The eye variants are
/// always a single piece, which the iris warp needs. `eyes` are the eye openings'
/// ellipses as (cx, cy, rx, ry) in base UV, left then right, the same for every variant.
#[derive(Clone, Copy, Debug)]
pub struct Portrait {
    pub name: &'static str,
    pub base: &'static str,
    pub parts_texture: &'static str,
    pub base_size: (u32, u32),
    pub parts_size: (u32, u32),
    pub parts: [&'static [Part]; 7],
    pub eyes: [[f32; 4]; 2],
}

pub const PART_ORDER: [&str; 7] = [
    "eyes_center_l",
    "eyes_center_r",
    "eyes_left_l",
    "eyes_left_r",
    "mouth_smile",
    "mouth_sad",
    "mouth_angry",
];

pub const PORTRAITS: [Portrait; 3] = [
    // Mona Lisa (Leonardo da Vinci, c. 1503-1506); the sheet is the user's edit
    Portrait {
        name: "mona",
        base: "portrait_mona.bmp",
        parts_texture: "portrait_mona_parts.bmp",
        base_size: (861, 1008),
        parts_size: (1024, 256),
        parts: [
            // eyes_center_l (ncc 0.57)
            &[Part {
                atlas: [0.18555, 0.58594, 0.32812, 0.92969],
                place: [0.32404, 0.15179, 0.40883, 0.19544],
            }],
            // eyes_center_r (ncc 0.61)
            &[Part {
                atlas: [0.79590, 0.01562, 0.97754, 0.42578],
                place: [0.41580, 0.14683, 0.52381, 0.19891],
            }],
            // eyes_left_l (ncc 0.58)
            &[Part {
                atlas: [0.33594, 0.58594, 0.47852, 0.92578],
                place: [0.32520, 0.15179, 0.40999, 0.19494],
            }],
            // eyes_left_r (ncc 0.63)
            &[Part {
                atlas: [0.00391, 0.58594, 0.17773, 0.97656],
                place: [0.42044, 0.14683, 0.52381, 0.19643],
            }],
            // mouth_smile (ncc 0.52)
            &[Part {
                atlas: [0.27637, 0.01562, 0.54102, 0.52344],
                place: [0.33914, 0.24603, 0.49652, 0.31052],
            }],
            // mouth_sad (ncc 0.50)
            &[Part {
                atlas: [0.54883, 0.01562, 0.78809, 0.51172],
                place: [0.33798, 0.24702, 0.48026, 0.31002],
            }],
            // mouth_angry (ncc 0.48)
            &[Part {
                atlas: [0.00391, 0.01562, 0.26855, 0.55469],
                place: [0.33449, 0.24504, 0.49187, 0.31349],
            }],
        ],
        eyes: [[0.37121, 0.17439, 0.02571, 0.00804], [0.47312, 0.17294, 0.03419, 0.00952]],
    },
    // Girl with a Pearl Earring (Johannes Vermeer, c. 1665); the sheet is the user's edit
    Portrait {
        name: "vermeer",
        base: "portrait_vermeer.bmp",
        parts_texture: "portrait_vermeer_parts.bmp",
        base_size: (534, 531),
        parts_size: (1024, 356),
        parts: [
            // eyes_center_l (ncc 0.83)
            &[Part {
                atlas: [0.00391, 0.01124, 0.13672, 0.51124],
                place: [0.30150, 0.28060, 0.42884, 0.44821],
            }],
            // eyes_center_r (ncc 0.83)
            &[Part {
                atlas: [0.14453, 0.01124, 0.36816, 0.51124],
                place: [0.39700, 0.28060, 0.61142, 0.44821],
            }],
            // eyes_left_l (ncc 0.83)
            &[Part {
                atlas: [0.37598, 0.01124, 0.50879, 0.51124],
                place: [0.30150, 0.28060, 0.42884, 0.44821],
            }],
            // eyes_left_r (ncc 0.83)
            &[Part {
                atlas: [0.51660, 0.01124, 0.74023, 0.51124],
                place: [0.39700, 0.28060, 0.61142, 0.44821],
            }],
            // mouth_smile (ncc 0.81)
            &[Part {
                atlas: [0.00391, 0.53371, 0.29688, 0.98876],
                place: [0.30712, 0.46893, 0.58801, 0.62147],
            }],
            // mouth_sad (ncc 0.81)
            &[Part {
                atlas: [0.30469, 0.53371, 0.59668, 0.98876],
                place: [0.30712, 0.46893, 0.58708, 0.62147],
            }],
            // mouth_angry (ncc 0.81)
            &[Part {
                atlas: [0.60449, 0.53371, 0.89844, 0.98876],
                place: [0.30712, 0.46893, 0.58895, 0.62147],
            }],
        ],
        eyes: [[0.36423, 0.34284, 0.02528, 0.01271], [0.47154, 0.35725, 0.03202, 0.01356]],
    },
    // The Laughing Cavalier (Frans Hals, 1624); the sheet is the user's edit
    Portrait {
        name: "cavalier",
        base: "portrait_cavalier.bmp",
        parts_texture: "portrait_cavalier_parts.bmp",
        base_size: (491, 469),
        parts_size: (512, 456),
        parts: [
            // eyes_center_l (ncc -0.09)
            &[Part {
                atlas: [0.15234, 0.69737, 0.35156, 0.84430],
                place: [0.21181, 0.36674, 0.31568, 0.43817],
            }],
            // eyes_center_r (ncc 0.17)
            &[Part {
                atlas: [0.32422, 0.48246, 0.61914, 0.66667],
                place: [0.32170, 0.33465, 0.47912, 0.42634],
            }],
            // eyes_left_l (ncc 0.28)
            &[Part {
                atlas: [0.36719, 0.69737, 0.57227, 0.83991],
                place: [0.20978, 0.36887, 0.31670, 0.43817],
            }],
            // eyes_left_r (ncc 0.23)
            &[Part {
                atlas: [0.29297, 0.25877, 0.58203, 0.46053],
                place: [0.32165, 0.33461, 0.47749, 0.43603],
            }],
            // mouth_smile: lips (ncc -0.37), goatee (ncc -0.08), lm (ncc -0.53), rm (ncc -0.33)
            &[
                Part {
                    atlas: [0.58789, 0.69737, 0.81445, 0.80921],
                    place: [0.25080, 0.49924, 0.41955, 0.57691],
                },
                Part {
                    atlas: [0.00781, 0.69737, 0.13672, 0.85526],
                    place: [0.24585, 0.56229, 0.38987, 0.72677],
                },
                Part {
                    atlas: [0.56445, 0.00877, 0.82422, 0.21491],
                    place: [0.21135, 0.44940, 0.36233, 0.56112],
                },
                Part {
                    atlas: [0.00781, 0.00877, 0.25586, 0.24123],
                    place: [0.31090, 0.38944, 0.52755, 0.57875],
                },
            ],
            // mouth_sad: lips (ncc -0.26), goatee (ncc -0.12), lm (ncc -0.47), rm (ncc -0.19)
            &[
                Part {
                    atlas: [0.00781, 0.87281, 0.22656, 0.98465],
                    place: [0.25705, 0.49938, 0.41619, 0.57525],
                },
                Part {
                    atlas: [0.63477, 0.48246, 0.75977, 0.64254],
                    place: [0.24589, 0.56446, 0.38493, 0.73049],
                },
                Part {
                    atlas: [0.00781, 0.25877, 0.27734, 0.46491],
                    place: [0.20524, 0.45793, 0.36189, 0.56965],
                },
                Part {
                    atlas: [0.00781, 0.48246, 0.30859, 0.67982],
                    place: [0.31198, 0.43748, 0.53311, 0.57278],
                },
            ],
            // mouth_angry: lips (ncc -0.23), goatee (ncc -0.11), lm (ncc -0.45), rm (ncc -0.24)
            &[
                Part {
                    atlas: [0.24219, 0.87281, 0.44531, 0.97149],
                    place: [0.25001, 0.49842, 0.42175, 0.57621],
                },
                Part {
                    atlas: [0.77539, 0.48246, 0.91211, 0.64254],
                    place: [0.24412, 0.56261, 0.39160, 0.72362],
                },
                Part {
                    atlas: [0.27148, 0.00877, 0.54883, 0.23465],
                    place: [0.20331, 0.45378, 0.36064, 0.57325],
                },
                Part {
                    atlas: [0.59766, 0.25877, 0.88477, 0.46053],
                    place: [0.31380, 0.45005, 0.53275, 0.59351],
                },
            ],
        ],
        eyes: [[0.26360, 0.40680, 0.03340, 0.01665], [0.39989, 0.38923, 0.05213, 0.02292]],
    },
];
