//! EXT: 2D drawing -- sprites, text, filled rectangles. Not part of the C++ port.
//!
//! The original engine has no 2D layer, no text and no alpha blending anywhere. This module
//! adds a minimal one on top of the ported primitives: every draw is `quad.obj` through
//! `Shaders/ui.*`, positioned by a scale/translate matrix that maps the unit quad straight into
//! normalised device coordinates (so no projection is involved), sampling a sub-rectangle of an
//! atlas with a colour tint, with blending enabled for the duration of the call.
//!
//! # Coordinates
//!
//! Screen space is **pixels from the top-left**, in the drawable's physical size (what the
//! engine already feeds to `glViewport`). Atlas rectangles are top-origin pixels too; the
//! flip to GL's bottom-origin texture space happens once, in `ui.vert`.
//!
//! # Assets
//!
//! `Textures/ui_cursors.bmp`, `Textures/ui_font.bmp` and `Textures/ui_title.bmp` are 32-bit
//! BMPs generated by `tools/gen_ui.py`, which also writes `ui_atlas.rs` with every rectangle as
//! a const.
//!
//! There are two faces. The interface face is Playpen Sans Bold, baked at 176 px, and sets
//! every word the menus say. The title face is Henny Penny, baked at 224 px, and sets one --
//! the game's name, `ui_atlas::TITLE_TEXT` -- which is why its atlas holds only the eleven characters
//! that name uses. Both are vendored under `assets/fonts/` so the atlases are reproducible on
//! any machine; [`draw_text`] and [`draw_title`] scale them to any size.
//!
//! [`draw_text`]: Ui::draw_text
//! [`draw_title`]: Ui::draw_title

use crate::ext::ui_atlas::{
    Glyph, Sprite, CURSOR_ATLAS, FONT_ATLAS, FONT_SIZE, GLYPHS, TITLE_ATLAS, TITLE_FONT_SIZE,
    TITLE_GLYPHS,
};
use crate::mesh::Mesh;
use crate::resources::Resources;
use crate::shader::Shader;
use crate::texture::Texture;
use crate::vector::{Matrix4, Vector3};
use glow::HasContext;
use std::rc::Rc;

/// RGBA colour, 0..1.
pub type Color = [f32; 4];
pub const WHITE: Color = [1.0, 1.0, 1.0, 1.0];
pub const GOLD: Color = [1.0, 0.82, 0.25, 1.0];
pub const DIM: Color = [0.35, 0.35, 0.35, 1.0];

#[derive(Clone, Copy, PartialEq)]
pub enum Align {
    Left,
    Center,
    Right,
}

/// Which of the two baked faces a string is set in.
///
/// Not public, and there is no argument anywhere that chooses one: [`Ui::draw_text`] is always
/// the interface face and [`Ui::draw_title`] is always the title face. That is the whole
/// safeguard against the title atlas -- which holds only the characters of `ui_atlas::TITLE_TEXT` --
/// being asked for a string it has no glyphs for, which would come out silently full of holes.
#[derive(Clone, Copy, PartialEq)]
enum Face {
    Ui,
    Title,
}

impl Face {
    /// The size this face was baked at, and its atlas in pixels.
    fn metrics(self) -> (f32, (f32, f32)) {
        match self {
            Face::Ui => (FONT_SIZE, (FONT_ATLAS.0 as f32, FONT_ATLAS.1 as f32)),
            Face::Title => (TITLE_FONT_SIZE, (TITLE_ATLAS.0 as f32, TITLE_ATLAS.1 as f32)),
        }
    }

    /// By value rather than by reference: `Glyph` is seven numbers, and the title table is a
    /// `const`, which has no address to borrow.
    fn glyph(self, c: char) -> Option<Glyph> {
        match self {
            Face::Ui => {
                let i = c as u32;
                (32..=126).contains(&i).then(|| GLYPHS[(i - 32) as usize])
            }
            Face::Title => TITLE_GLYPHS.iter().find(|(g, _)| *g == c).map(|&(_, g)| g),
        }
    }
}

pub struct Ui {
    gl: Rc<glow::Context>,
    quad: Rc<Mesh>,
    shader: Rc<Shader>,
    cursors: Rc<Texture>,
    font: Rc<Texture>,
    title: Rc<Texture>,
    white: Rc<Texture>,
    /// Drawable size in physical pixels, refreshed by `begin` each frame.
    width: f32,
    height: f32,
}

impl Ui {
    pub fn new(gl: &Rc<glow::Context>, res: &Resources) -> Ui {
        Ui {
            gl: Rc::clone(gl),
            quad: res.acquire_mesh("quad.obj"),
            shader: res.acquire_shader("ui"),
            cursors: res.acquire_texture("ui_cursors.bmp", 1, 1),
            font: res.acquire_texture("ui_font.bmp", 1, 1),
            title: res.acquire_texture("ui_title.bmp", 1, 1),
            white: res.acquire_texture("white.bmp", 1, 1),
            width: 1.0,
            height: 1.0,
        }
    }

    /// Set up GL state for a batch of 2D draws. Pair with `end`.
    pub fn begin(&mut self, width: i32, height: i32) {
        self.width = width.max(1) as f32;
        self.height = height.max(1) as f32;
        unsafe {
            self.gl.disable(glow::DEPTH_TEST);
            self.gl.enable(glow::BLEND);
            self.gl.blend_func(glow::SRC_ALPHA, glow::ONE_MINUS_SRC_ALPHA);
            // Both faces: the quad is front-facing, but nothing here should ever cull.
            self.gl.disable(glow::CULL_FACE);
        }
        self.shader.use_program();
    }

    /// Restore the 3D state the ported renderer expects (Engine.cpp:421-425).
    pub fn end(&self) {
        unsafe {
            self.gl.disable(glow::BLEND);
            self.gl.enable(glow::CULL_FACE);
            self.gl.enable(glow::DEPTH_TEST);
        }
    }

    pub fn size(&self) -> (f32, f32) {
        (self.width, self.height)
    }

    /// Pixel rect (top-left origin) -> the NDC scale/translate matrix for the unit quad.
    fn rect_matrix(&self, x: f32, y: f32, w: f32, h: f32) -> Matrix4 {
        let sx = w / self.width;
        let sy = h / self.height;
        let cx = (x + w * 0.5) / self.width * 2.0 - 1.0;
        let cy = 1.0 - (y + h * 0.5) / self.height * 2.0;
        Matrix4::trans(Vector3::new(cx, cy, 0.0)) * Matrix4::scale(Vector3::new(sx, sy, 1.0))
    }

    fn draw_quad(&self, tex: &Texture, x: f32, y: f32, w: f32, h: f32, uv: [f32; 4], color: Color) {
        self.draw_quad_grad(tex, x, y, w, h, uv, color, color, [0.0, 0.0]);
    }

    /// The one draw call every other method here goes through. `color` at the start of
    /// `axis`, `color2` at its end; a zero axis is a flat tint.
    #[allow(clippy::too_many_arguments)] // it is one GL draw's worth of state, not a design
    fn draw_quad_grad(
        &self,
        tex: &Texture,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        uv: [f32; 4],
        color: Color,
        color2: Color,
        axis: [f32; 2],
    ) {
        tex.use_texture();
        let m = self.rect_matrix(x, y, w, h);
        self.shader.set_mvp(Some(&m), None);
        self.shader.set_vec4("uv_rect", uv);
        self.shader.set_vec4("color", color);
        // Always set, never left over from the last draw: an uninitialised `color2` would take
        // every flat fill to black across its own width.
        self.shader.set_vec4("color2", color2);
        self.shader.set_vec2("grad_axis", axis);
        self.quad.draw();
    }

    /// Solid rectangle.
    pub fn fill_rect(&self, x: f32, y: f32, w: f32, h: f32, color: Color) {
        self.draw_quad(&self.white, x, y, w, h, [0.0, 0.0, 1.0, 1.0], color);
    }

    /// Rectangle washed from `left` to `right` across its width, or top to bottom when
    /// `vertical`.
    ///
    /// What this is for: a menu drawn over a live scene needs the scene knocked back far
    /// enough to carry text, and a flat wash over the whole frame knocks back the part of the
    /// scene the player is meant to be looking at as well. A gradient puts the darkness only
    /// where the words are. One draw rather than a run of strips, because a strip-wise
    /// approximation of a smooth ramp bands visibly at 8 bits -- which is exactly what it was
    /// brought in to avoid.
    pub fn fill_rect_grad(
        &self,
        x: f32,
        y: f32,
        w: f32,
        h: f32,
        from: Color,
        to: Color,
        vertical: bool,
    ) {
        let axis = if vertical { [0.0, 1.0] } else { [1.0, 0.0] };
        self.draw_quad_grad(&self.white, x, y, w, h, [0.0, 0.0, 1.0, 1.0], from, to, axis);
    }

    /// Cursor-atlas sprite, centred on (cx, cy), scaled to `h` pixels tall (aspect preserved).
    pub fn draw_cursor(&self, s: &Sprite, cx: f32, cy: f32, h: f32, color: Color) {
        let (aw, ah) = (CURSOR_ATLAS.0 as f32, CURSOR_ATLAS.1 as f32);
        let uv =
            [s.x as f32 / aw, s.y as f32 / ah, (s.x + s.w) as f32 / aw, (s.y + s.h) as f32 / ah];
        let w = h * s.w as f32 / s.h as f32;
        self.draw_quad(&self.cursors, cx - w * 0.5, cy - h * 0.5, w, h, uv, color);
    }

    /// Width in pixels of `text` set in `face` at `size_px`.
    fn measure_in(&self, face: Face, text: &str, size_px: f32) -> f32 {
        let k = size_px / face.metrics().0;
        text.chars().map(|c| face.glyph(c).map_or(0.0, |g| g.adv as f32 * k)).sum()
    }

    /// Draw `text` in `face` with the top of its line box at `y`.
    fn draw_in(
        &self,
        face: Face,
        text: &str,
        x: f32,
        y: f32,
        size_px: f32,
        color: Color,
        align: Align,
    ) {
        let (baked, (aw, ah)) = face.metrics();
        let k = size_px / baked;
        let total = self.measure_in(face, text, size_px);
        let mut pen = match align {
            Align::Left => x,
            Align::Center => x - total * 0.5,
            Align::Right => x - total,
        };
        let atlas = match face {
            Face::Ui => &self.font,
            Face::Title => &self.title,
        };
        for c in text.chars() {
            let Some(g) = face.glyph(c) else { continue };
            // The space is baked as a 1 px sliver with nothing in it; drawing it is a quad
            // and a state change for no pixels.
            if g.w > 1 || c != ' ' {
                let gx = pen + g.bx as f32 * k;
                // `by` is measured down from the top of the line box, which is what `y` is.
                let gy = y + g.by as f32 * k;
                let uv = [
                    g.x as f32 / aw,
                    g.y as f32 / ah,
                    (g.x + g.w) as f32 / aw,
                    (g.y + g.h) as f32 / ah,
                ];
                self.draw_quad(atlas, gx, gy, g.w as f32 * k, g.h as f32 * k, uv, color);
            }
            pen += g.adv as f32 * k;
        }
    }

    /// Width in pixels of `text` drawn at `size_px`.
    pub fn measure(&self, text: &str, size_px: f32) -> f32 {
        self.measure_in(Face::Ui, text, size_px)
    }

    /// Draw `text` with its baseline-top at `y` (i.e. `y` is the top of the line box).
    pub fn draw_text(&self, text: &str, x: f32, y: f32, size_px: f32, color: Color, align: Align) {
        self.draw_in(Face::Ui, text, x, y, size_px, color, align);
    }

    /// The game's name, set in the title face. `text` is `ui_atlas::TITLE_TEXT` -- it is a
    /// parameter only so the caller reads as a draw call; no other string has glyphs here.
    pub fn draw_title(&self, text: &str, x: f32, y: f32, size_px: f32, color: Color, align: Align) {
        self.draw_in(Face::Title, text, x, y, size_px, color, align);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn atlas_tables_are_sane() {
        // Every printable ASCII glyph must be present and fit inside the interface atlas.
        for (i, g) in GLYPHS.iter().enumerate() {
            assert!(g.x + g.w <= FONT_ATLAS.0, "glyph {} overruns atlas width", i + 32);
            assert!(g.y + g.h <= FONT_ATLAS.1, "glyph {} overruns atlas height", i + 32);
            assert!(g.adv >= 0);
        }
        for (c, g) in TITLE_GLYPHS {
            assert!(g.x + g.w <= TITLE_ATLAS.0, "title glyph {c:?} overruns atlas width");
            assert!(g.y + g.h <= TITLE_ATLAS.1, "title glyph {c:?} overruns atlas height");
            assert!(g.adv >= 0);
        }
        for s in [
            &crate::ext::ui_atlas::CURSOR_DOT,
            &crate::ext::ui_atlas::CURSOR_OPEN,
            &crate::ext::ui_atlas::CURSOR_CLOSED,
        ] {
            assert!(s.x + s.w <= CURSOR_ATLAS.0 && s.y + s.h <= CURSOR_ATLAS.1);
        }
    }

    #[test]
    fn glyph_lookup_bounds() {
        assert!(Face::Ui.glyph('A').is_some());
        assert!(Face::Ui.glyph(' ').is_some());
        assert!(Face::Ui.glyph('\n').is_none());
        assert!(Face::Ui.glyph('é').is_none());
    }

    /// The title atlas is baked for one string, so the one string it is asked for has to be
    /// covered -- a missing glyph is skipped silently, and the name would be drawn with a
    /// letter or a space missing rather than not drawn at all. `tools/gen_ui.py` writes both
    /// the name and the table, so this can only fail if `ui_atlas.rs` was hand-edited or the
    /// generator was changed without being re-run.
    #[test]
    fn the_title_face_covers_the_name() {
        for c in crate::ext::ui_atlas::TITLE_TEXT.chars() {
            assert!(Face::Title.glyph(c).is_some(), "the title atlas has no glyph for {c:?}");
        }
        // And nothing else was baked into it, which is what keeps it a 1024x512 file.
        assert_eq!(
            TITLE_GLYPHS.len(),
            crate::ext::ui_atlas::TITLE_TEXT
                .chars()
                .collect::<std::collections::BTreeSet<_>>()
                .len()
        );
    }
}
