//! EXT: 2D drawing -- sprites, text, filled rectangles. Not part of the C++ port.
//!
//! The original engine has no 2D layer, no text and no alpha blending anywhere. This module
//! adds a minimal one on top of the ported primitives: every draw is `quad.obj` through
//! `Shaders/ui.*`, positioned by a scale/translate matrix that maps the unit quad straight into
//! normalised device coordinates (so no projection is involved), sampling a sub-rectangle of an
//! atlas with a colour tint, with blending enabled for the duration of the call.
//!
//! # Coordinates
//!
//! Screen space is **pixels from the top-left**, in the drawable's physical size (what the
//! engine already feeds to `glViewport`). Atlas rectangles are top-origin pixels too; the
//! flip to GL's bottom-origin texture space happens once, in `ui.vert`.
//!
//! # Assets
//!
//! `Textures/ui_cursors.bmp` and `Textures/ui_font.bmp` are 32-bit BMPs generated by
//! `tools/gen_ui.py`, which also writes `ui_atlas.rs` with every rectangle as a const. The font
//! is Roboto Condensed Bold baked at 72 px, vendored under `assets/fonts/` so the atlas is
//! reproducible on any machine; `draw_text` scales it to any size.

use crate::ext::ui_atlas::{
    Glyph, Sprite, CURSOR_ATLAS, FONT_ASCENT, FONT_ATLAS, FONT_SIZE, GLYPHS,
};
use crate::mesh::Mesh;
use crate::resources::Resources;
use crate::shader::Shader;
use crate::texture::Texture;
use crate::vector::{Matrix4, Vector3};
use glow::HasContext;
use std::rc::Rc;

/// RGBA colour, 0..1.
pub type Color = [f32; 4];
pub const WHITE: Color = [1.0, 1.0, 1.0, 1.0];
pub const GOLD: Color = [1.0, 0.82, 0.25, 1.0];
pub const DIM: Color = [0.35, 0.35, 0.35, 1.0];

#[derive(Clone, Copy, PartialEq)]
pub enum Align {
    Left,
    Center,
    Right,
}

pub struct Ui {
    gl: Rc<glow::Context>,
    quad: Rc<Mesh>,
    shader: Rc<Shader>,
    cursors: Rc<Texture>,
    font: Rc<Texture>,
    white: Rc<Texture>,
    /// Drawable size in physical pixels, refreshed by `begin` each frame.
    width: f32,
    height: f32,
}

impl Ui {
    pub fn new(gl: &Rc<glow::Context>, res: &Resources) -> Ui {
        Ui {
            gl: Rc::clone(gl),
            quad: res.acquire_mesh("quad.obj"),
            shader: res.acquire_shader("ui"),
            cursors: res.acquire_texture("ui_cursors.bmp", 1, 1),
            font: res.acquire_texture("ui_font.bmp", 1, 1),
            white: res.acquire_texture("white.bmp", 1, 1),
            width: 1.0,
            height: 1.0,
        }
    }

    /// Set up GL state for a batch of 2D draws. Pair with `end`.
    pub fn begin(&mut self, width: i32, height: i32) {
        self.width = width.max(1) as f32;
        self.height = height.max(1) as f32;
        unsafe {
            self.gl.disable(glow::DEPTH_TEST);
            self.gl.enable(glow::BLEND);
            self.gl.blend_func(glow::SRC_ALPHA, glow::ONE_MINUS_SRC_ALPHA);
            // Both faces: the quad is front-facing, but nothing here should ever cull.
            self.gl.disable(glow::CULL_FACE);
        }
        self.shader.use_program();
    }

    /// Restore the 3D state the ported renderer expects (Engine.cpp:421-425).
    pub fn end(&self) {
        unsafe {
            self.gl.disable(glow::BLEND);
            self.gl.enable(glow::CULL_FACE);
            self.gl.enable(glow::DEPTH_TEST);
        }
    }

    pub fn size(&self) -> (f32, f32) {
        (self.width, self.height)
    }

    /// Pixel rect (top-left origin) -> the NDC scale/translate matrix for the unit quad.
    fn rect_matrix(&self, x: f32, y: f32, w: f32, h: f32) -> Matrix4 {
        let sx = w / self.width;
        let sy = h / self.height;
        let cx = (x + w * 0.5) / self.width * 2.0 - 1.0;
        let cy = 1.0 - (y + h * 0.5) / self.height * 2.0;
        Matrix4::trans(Vector3::new(cx, cy, 0.0)) * Matrix4::scale(Vector3::new(sx, sy, 1.0))
    }

    fn draw_quad(&self, tex: &Texture, x: f32, y: f32, w: f32, h: f32, uv: [f32; 4], color: Color) {
        tex.use_texture();
        let m = self.rect_matrix(x, y, w, h);
        self.shader.set_mvp(Some(&m), None);
        self.shader.set_vec4("uv_rect", uv);
        self.shader.set_vec4("color", color);
        self.quad.draw();
    }

    /// Solid rectangle.
    pub fn fill_rect(&self, x: f32, y: f32, w: f32, h: f32, color: Color) {
        self.draw_quad(&self.white, x, y, w, h, [0.0, 0.0, 1.0, 1.0], color);
    }

    /// Cursor-atlas sprite, centred on (cx, cy), scaled to `h` pixels tall (aspect preserved).
    pub fn draw_cursor(&self, s: &Sprite, cx: f32, cy: f32, h: f32, color: Color) {
        let (aw, ah) = (CURSOR_ATLAS.0 as f32, CURSOR_ATLAS.1 as f32);
        let uv =
            [s.x as f32 / aw, s.y as f32 / ah, (s.x + s.w) as f32 / aw, (s.y + s.h) as f32 / ah];
        let w = h * s.w as f32 / s.h as f32;
        self.draw_quad(&self.cursors, cx - w * 0.5, cy - h * 0.5, w, h, uv, color);
    }

    fn glyph(c: char) -> Option<&'static Glyph> {
        let i = c as u32;
        if (32..=126).contains(&i) {
            Some(&GLYPHS[(i - 32) as usize])
        } else {
            None
        }
    }

    /// Width in pixels of `text` drawn at `size_px`.
    pub fn measure(&self, text: &str, size_px: f32) -> f32 {
        let k = size_px / FONT_SIZE;
        text.chars().map(|c| Self::glyph(c).map_or(0.0, |g| g.adv as f32 * k)).sum()
    }

    /// Draw `text` with its baseline-top at `y` (i.e. `y` is the top of the line box).
    pub fn draw_text(&self, text: &str, x: f32, y: f32, size_px: f32, color: Color, align: Align) {
        let k = size_px / FONT_SIZE;
        let total = self.measure(text, size_px);
        let mut pen = match align {
            Align::Left => x,
            Align::Center => x - total * 0.5,
            Align::Right => x - total,
        };
        let baseline = y + FONT_ASCENT * k;
        let (aw, ah) = (FONT_ATLAS.0 as f32, FONT_ATLAS.1 as f32);
        for c in text.chars() {
            let Some(g) = Self::glyph(c) else { continue };
            if g.w > 1 || c != ' ' {
                let gx = pen + g.bx as f32 * k;
                let gy = baseline - FONT_ASCENT * k + g.by as f32 * k;
                let uv = [
                    g.x as f32 / aw,
                    g.y as f32 / ah,
                    (g.x + g.w) as f32 / aw,
                    (g.y + g.h) as f32 / ah,
                ];
                self.draw_quad(&self.font, gx, gy, g.w as f32 * k, g.h as f32 * k, uv, color);
            }
            pen += g.adv as f32 * k;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn atlas_tables_are_sane() {
        // Every printable ASCII glyph must be present and fit inside the atlas.
        for (i, g) in GLYPHS.iter().enumerate() {
            assert!(g.x + g.w <= FONT_ATLAS.0, "glyph {} overruns atlas width", i + 32);
            assert!(g.y + g.h <= FONT_ATLAS.1, "glyph {} overruns atlas height", i + 32);
            assert!(g.adv >= 0);
        }
        for s in [
            &crate::ext::ui_atlas::CURSOR_DOT,
            &crate::ext::ui_atlas::CURSOR_OPEN,
            &crate::ext::ui_atlas::CURSOR_CLOSED,
        ] {
            assert!(s.x + s.w <= CURSOR_ATLAS.0 && s.y + s.h <= CURSOR_ATLAS.1);
        }
    }

    #[test]
    fn glyph_lookup_bounds() {
        assert!(Ui::glyph('A').is_some());
        assert!(Ui::glyph(' ').is_some());
        assert!(Ui::glyph('\n').is_none());
        assert!(Ui::glyph('é').is_none());
    }
}
