"""Generate Meshes/key.obj: the key that comes out of the Backrooms' portrait (src/ext/key.rs).

A flat key silhouette -- a ring bow, a shaft and two teeth -- extruded THICK metres, in the
engine's OBJ dialect (quads with `v/vt` indices; the loader computes flat normals per face and
keeps no `c` collider lines, the key collides through its hit sphere instead). Counter-clockwise
winding seen from outside every face: the engine culls back faces.

THE SAME SILHOUETTE IS PAINTED ON THE CANVAS by Shaders/painting.frag (`sdKey`), and the two
must agree or the 3D key that emerges will not be the key that was painted. The numbers below
are duplicated there, under the same names, with a comment pointing back here.

The key's own frame: x along its length (bow at -x, tip at +x), y across it (the teeth hang
toward -y), z through its thickness; the origin is the midpoint of its length on the shaft's
centreline, so the bounding radius the loader measures is half the length plus a little. The
painting lays this frame onto its picture plane (x along the plane's u, y along v) and the key
lies there sideways, as it is painted.

Run from the repository root:  python3 tools/gen_key.py
"""
import math
import os

# ── The silhouette, in metres (mirrored in Shaders/painting.frag; a test in painting.rs
# reads both files and the generated mesh and fails when they disagree -- run
# `cargo test --release the_shader_the_generator` after changing a number here) ────────────
# 9 cm: as long as the sweet spot's grazing view of the canvas can show between the frame's
# uprights (painting.rs, `KEY_ON_PLANE`).
LENGTH = 0.09        # bow's far rim to the tip
BOW_R = 0.019        # ring's outer radius
BOW_HOLE = 0.010     # ring's inner radius
BOW_CX = -LENGTH / 2 + BOW_R
SHAFT_HW = 0.004     # half the shaft's width
SHAFT_X0 = BOW_CX + BOW_R * 0.7   # starts inside the ring, so the two are one piece
SHAFT_X1 = LENGTH / 2
# Teeth: (x0, x1, depth) -- a rectangle from the centreline down to y = -depth.
TEETH = [(0.034, 0.045, 0.013), (0.020, 0.028, 0.010)]
THICK = 0.008
RING_SEGMENTS = 32

OUT = os.path.join(os.path.dirname(__file__), "..", "Meshes", "key.obj")

verts = []   # (x, y, z)
uvs = []     # (u, v)
faces = []   # [(vi, ti), ...] quads, 1-based


def vert(x, y, z):
    verts.append((x, y, z))
    return len(verts)


def uv(x, y):
    # Planar map of the key's bounding box onto the texture: the gold is a flat tone, so
    # this only has to be continuous.
    uvs.append(((x + LENGTH / 2) / LENGTH, (y + BOW_R) / (2 * BOW_R)))
    return len(uvs)


def quad(a, b, c, d):
    """Four (vertex, uv) pairs, counter-clockwise seen from outside."""
    faces.append([a, b, c, d])


def box(x0, x1, y0, y1):
    h = THICK / 2
    corners = {}
    for (x, y) in [(x0, y0), (x1, y0), (x1, y1), (x0, y1)]:
        for z in (-h, h):
            corners[(x, y, z)] = (vert(x, y, z), uv(x, y))
    c = lambda x, y, z: corners[(x, y, z)]
    # Front (+z) and back (-z) caps.
    quad(c(x0, y0, h), c(x1, y0, h), c(x1, y1, h), c(x0, y1, h))
    quad(c(x0, y1, -h), c(x1, y1, -h), c(x1, y0, -h), c(x0, y0, -h))
    # Four walls.
    quad(c(x0, y0, -h), c(x1, y0, -h), c(x1, y0, h), c(x0, y0, h))   # -y
    quad(c(x1, y0, -h), c(x1, y1, -h), c(x1, y1, h), c(x1, y0, h))   # +x
    quad(c(x1, y1, -h), c(x0, y1, -h), c(x0, y1, h), c(x1, y1, h))   # +y
    quad(c(x0, y1, -h), c(x0, y0, -h), c(x0, y0, h), c(x0, y1, h))   # -x


def ring(cx, cy, r_out, r_in):
    h = THICK / 2
    n = RING_SEGMENTS
    pts = []
    for i in range(n):
        a = 2 * math.pi * i / n
        ca, sa = math.cos(a), math.sin(a)
        o = (cx + r_out * ca, cy + r_out * sa)
        inner = (cx + r_in * ca, cy + r_in * sa)
        pts.append({
            "of": (vert(*o, h), uv(*o)), "ob": (vert(*o, -h), uv(*o)),
            "if": (vert(*inner, h), uv(*inner)), "ib": (vert(*inner, -h), uv(*inner)),
        })
    for i in range(n):
        p, q = pts[i], pts[(i + 1) % n]
        quad(p["of"], q["of"], q["if"], p["if"])   # front cap, CCW from +z
        quad(p["ib"], q["ib"], q["ob"], p["ob"])   # back cap, CCW from -z
        quad(p["ob"], q["ob"], q["of"], p["of"])   # outer wall
        quad(p["if"], q["if"], q["ib"], p["ib"])   # inner wall


ring(BOW_CX, 0.0, BOW_R, BOW_HOLE)
box(SHAFT_X0, SHAFT_X1, -SHAFT_HW, SHAFT_HW)
for (x0, x1, depth) in TEETH:
    box(x0, x1, -depth, 0.0)

with open(OUT, "w") as f:
    f.write("# EXT: not from the original NonEuclidean asset set. Generated by tools/gen_key.py;\n")
    f.write("# edit that, not this. A flat key, %g m long, %g mm thick, no colliders.\n" % (LENGTH, THICK * 1e3))
    for (x, y, z) in verts:
        f.write("v %.5f %.5f %.5f\n" % (x, y, z))
    for (u, v) in uvs:
        f.write("vt %.4f %.4f\n" % (u, v))
    for q in faces:
        f.write("f " + " ".join("%d/%d" % (vi, ti) for (vi, ti) in q) + "\n")

print("wrote %s: %d vertices, %d quads" % (os.path.normpath(OUT), len(verts), len(faces)))
