"""Generate the meadow: rolling-hill terrain with a walk shell, and a tileable grass texture.

Performance is the brief, so everything expensive is done HERE, offline:
  * Meshes/meadow.obj     -- heightfield mesh. Smooth normals are smuggled through the engine's
                             3-component `vt` channel (the parser discards `vn` and recomputes
                             flat per-face normals, Mesh.cpp:187), so the hills shade smoothly
                             instead of showing facets. `c` lines carry gradient-tilted
                             rectangle colliders on a coarser grid (same scheme as the
                             Relativity walk shell).
  * Textures/grass_noise.bmp -- tileable 32-bit noise: R = patchiness (low freq), G = blade
                             streaks (high freq, anisotropic), B = mid-frequency variation.
                             The grass shader is then two texture taps, no noise math.
"""
import numpy as np, struct
from PIL import Image

rng = np.random.default_rng(7)

# ── Periodic value noise (tileable by construction) ───────────────────────────────────────────
def value_noise(shape, period, octaves=5, lacunarity=2.0, gain=0.5, stretch=(1, 1)):
    h, w = shape
    out = np.zeros((h, w), np.float32)
    amp, total = 1.0, 0.0
    p = period
    for _ in range(octaves):
        px, pz = max(2, int(p * stretch[0])), max(2, int(p * stretch[1]))
        lattice = rng.random((pz, px)).astype(np.float32)
        ys = np.linspace(0, pz, h, endpoint=False)
        xs = np.linspace(0, px, w, endpoint=False)
        y0 = np.floor(ys).astype(int); x0 = np.floor(xs).astype(int)
        fy = (ys - y0)[:, None]; fx = (xs - x0)[None, :]
        fy = fy * fy * (3 - 2 * fy); fx = fx * fx * (3 - 2 * fx)
        y1 = (y0 + 1) % pz; x1 = (x0 + 1) % px
        a = lattice[y0][:, x0]; b = lattice[y0][:, x1]
        c = lattice[y1][:, x0]; d = lattice[y1][:, x1]
        n = (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy
        out += n * amp; total += amp
        amp *= gain; p *= lacunarity
    return out / total

# ── Terrain ───────────────────────────────────────────────────────────────────────────────────
SIZE      = 220.0     # world units per side
VIS_N     = 120       # visual grid cells per side
COL_N     = 44        # collider cells per side (44^2 = 1936 colliders)
AMP       = 9.0       # hill height range
hf = value_noise((VIS_N + 1, VIS_N + 1), period=3, octaves=4, gain=0.45)
hf = (hf - hf.min()) / (hf.max() - hf.min())
# Ease so valleys are broad and tops rounded -- the Bliss look, not jagged noise.
hf = hf * hf * (3 - 2 * hf)
H = hf * AMP
# Flatten a spawn plateau near the centre so the player starts on solid, level ground.
cy, cx = VIS_N // 2, VIS_N // 2
yy, xx = np.mgrid[0:VIS_N + 1, 0:VIS_N + 1]
plateau = np.exp(-(((yy - cy) ** 2 + (xx - cx) ** 2) / (2 * 6.0 ** 2)))
H = H * (1 - plateau) + H[cy, cx] * plateau

step = SIZE / VIS_N
def world(i, j):
    return (-SIZE / 2 + j * step, float(H[i, j]), -SIZE / 2 + i * step)

# Smooth normals by central differences.
dzdx = np.gradient(H, step, axis=1)
dzdz = np.gradient(H, step, axis=0)
nx, ny, nz = -dzdx, np.ones_like(H), -dzdz
ln = np.sqrt(nx * nx + ny * ny + nz * nz); nx /= ln; ny /= ln; nz /= ln
max_grad = float(np.max(np.sqrt(dzdx ** 2 + dzdz ** 2)))

lines = ["# EXT asset: rolling-hill meadow, generated by tools/gen_meadow.py.",
         "# `vt` carries the SMOOTH NORMAL (3 components) -- the engine recomputes flat normals",
         "# from faces, so this is the only way to ship smooth shading. The grass shader reads",
         "# in_uv as the normal and derives texture coordinates from world position instead.",
         "# `c` lines: gradient-tilted rectangle colliders on a coarser grid (walk shell)."]
for i in range(VIS_N + 1):
    for j in range(VIS_N + 1):
        x, y, z = world(i, j)
        lines.append(f"v {x:.3f} {y:.3f} {z:.3f}")
for i in range(VIS_N + 1):
    for j in range(VIS_N + 1):
        lines.append(f"vt {nx[i, j]:.4f} {ny[i, j]:.4f} {nz[i, j]:.4f}")
def idx(i, j): return i * (VIS_N + 1) + j + 1
for i in range(VIS_N):
    for j in range(VIS_N):
        a, b, c, d = idx(i, j), idx(i, j + 1), idx(i + 1, j + 1), idx(i + 1, j)
        # CCW seen from above (+Y): the engine culls back faces.
        lines.append(f"f {a}/{a} {d}/{d} {c}/{c}")
        lines.append(f"f {a}/{a} {c}/{c} {b}/{b}")

# Colliders: one tilted rectangle per coarse cell, exactly-orthogonal legs, slightly oversized.
vbase = (VIS_N + 1) ** 2
cverts, ccols = [], []
cstep = SIZE / COL_N
grown = 1.12

def sample(xw, zw):
    """Bilinear height at a world position -- the collider grid and the visual grid have
    different spacings, so colliders must sample by POSITION, never by integer index. (The
    first version used `VIS_N // COL_N` and every collider landed on the wrong hill.)"""
    fj = (xw + SIZE / 2) / step
    fi = (zw + SIZE / 2) / step
    i0 = int(np.clip(np.floor(fi), 0, VIS_N - 1)); j0 = int(np.clip(np.floor(fj), 0, VIS_N - 1))
    ti, tj = fi - i0, fj - j0
    return float((H[i0, j0] * (1 - tj) + H[i0, j0 + 1] * tj) * (1 - ti)
                 + (H[i0 + 1, j0] * (1 - tj) + H[i0 + 1, j0 + 1] * tj) * ti)

for ci in range(COL_N):
    for cj in range(COL_N):
        cxw = -SIZE / 2 + (cj + 0.5) * cstep
        czw = -SIZE / 2 + (ci + 0.5) * cstep
        ymid = sample(cxw, czw)
        e = cstep * 0.5
        gx = (sample(min(cxw + e, SIZE/2 - 0.01), czw) - sample(max(cxw - e, -SIZE/2), czw)) / (2 * e)
        gz = (sample(cxw, min(czw + e, SIZE/2 - 0.01)) - sample(cxw, max(czw - e, -SIZE/2))) / (2 * e)
        U = np.array([1.0, gx, 0.0]); V = np.array([0.0, gz, 1.0])
        V = V - U * (U @ V) / (U @ U)              # Gram-Schmidt -> exactly orthogonal
        h = cstep * 0.5 * grown
        U = U * h; V = V * (h / V[2])
        C = np.array([cxw, ymid, czw])
        A, B, D = C - U - V, C + U - V, C - U + V
        k = vbase + len(cverts) + 1
        cverts += [A, B, D]; ccols.append((k, k + 1, k + 2))
for v in cverts:
    lines.append(f"v {v[0]:.3f} {v[1]:.3f} {v[2]:.3f}")
for a, b, c in ccols:
    lines.append(f"c {a} {b} {c}")
open("Meshes/meadow.obj", "w").write("\n".join(lines) + "\n")
spawn_y = float(H[cy, cx])
print(f"meadow.obj: {(VIS_N+1)**2} verts, {2*VIS_N*VIS_N} tris, {len(ccols)} colliders, "
      f"max gradient {max_grad:.2f} (normal.y {1/np.sqrt(1+max_grad**2):.2f}), "
      f"spawn plateau y={spawn_y:.2f}")
assert 1 / np.sqrt(1 + max_grad ** 2) > 0.75, "too steep for the player somewhere"

# ── Grass noise texture (tileable, 32-bit so the loader picks LINEAR + mipmaps) ──────────────
T = 512
patch  = value_noise((T, T), period=4, octaves=4, gain=0.5)
blades = value_noise((T, T), period=96, octaves=3, gain=0.6, stretch=(0.35, 1.0))
mid    = value_noise((T, T), period=16, octaves=3, gain=0.5)
def norm01(a): return (a - a.min()) / (a.max() - a.min())
img = np.stack([norm01(patch), norm01(blades), norm01(mid), np.ones((T, T))], -1)
img = (img * 255).astype(np.uint8)
im = Image.fromarray(img, "RGBA")
# Write as 32-bit BMP, bottom-first rows.
px = np.array(im)[::-1]
data = px[..., [2, 1, 0, 3]].tobytes()
hdr  = struct.pack("<2sIHHI", b"BM", 54 + len(data), 0, 0, 54)
hdr += struct.pack("<IiiHHIIiiII", 40, T, T, 1, 32, 0, len(data), 2835, 2835, 0, 0)
open("Textures/grass_noise.bmp", "wb").write(hdr + data)
print(f"grass_noise.bmp: {T}x{T} RGBA (R patch, G blades, B mid)")
